apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
images:
  - name: abhishek00007/newnode
    newName: abhishek00007/newnode
    newTag: v1
