version: 2.1

jobs:
  runner-test:
    docker:
      - image: circleci/node:12
    steps:   
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Building docker image
          command: |
            echo $docker_password | docker login -u abhishek00007 --password-stdin
            docker build -t abhishek00007/newnode .
            docker push abhishek00007/newnode
            
workflows:
  testing:
    jobs:
      - runner-test
