version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    docker:
      - image: circleci/node:14.17-browsers
    steps:
      - checkout
      - run: docker login -u abhishek00007 -p abhishek@123
      - run: docker build -t abhishek00007/newnode .
      - run: docker push abhishek00007/newnode
