version: 2.1

orbs:
  docker: circleci/docker@2.4.0         # Replace x.y.z with the desired version of the Docker Orb

jobs:
  build-and-push:
    executor: docker/default
    steps:
      - checkout
      
      # Use the Docker Orb commands to build and push the Docker image
      - docker/build:
          image: abhishek00007/node-orb:latest  # Specify the image to build
      - docker/push:
          image: abhishek00007/node-orb:latest  # Specify the image to push
          registry: https://hub.docker.com/  # Replace with your registry URL
          username: $DOCKERHUB_USERNAME  # Use environment variables or secrets for credentials
          password: $docker_password

workflows:
  testing:
    jobs:
      - build-and-push
