version: 2.1

jobs:
  buildAndPush:
    docker:
      - image: circleci/node:12
    steps:   
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Building docker image
          command: |
            echo $docker_password | docker login -u abhishek00007 --password-stdin
            docker build -t abhishek00007/newnode:latest .
            docker push abhishek00007/newnode:latest
  deployment:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: deploy-to-AKS
          command: |
            sudo apt-get update
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            az login --service-principal -u 79d9244d-c692-4f4e-869c-995779c1ec31 -p r2c8Q~_UDX7m3RbOUcNRg-ttTPAp4qczWSzLgcw-
            az account set --subscription 1ce8bf33-286c-42dd-b193-10c310dd14b7
            az aks get-credentials --resource-group speakeasy --name speakeasy
            kubectl apply -f deployment.yml
            kubectl set image deployment/nodejs nodejs-aks-app=abhishek00007/newnode:$CIRCLE_BUILD_NUM


workflows:
  testing:
    jobs:
      - buildAndPush
      - deployment
          # requires:
          #   - buildAndPush

