version: 2.1

jobs:
  buildAndPush:
    docker:
      - image: cimg/base:2021.04
    steps:   
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building docker image
          command: |
            echo $docker_password | docker login -u abhishek00007 --password-stdin
            docker build -t abhishek00007/newnode:latest .
            docker push abhishek00007/newnode:latest
  deployment:
    docker:
      - image: abhishek00007/runner1
    steps:
      - checkout
      - run:
          name: deploy-to-AKS
          command: |            
            az login --service-principal -u f42f382a-55c6-47fc-82f5-61c645c92800 -p NrS8Q~iVlkLkh95j-jL2bGqw4Xb.gQkikt62jcFR --tenant bddba232-ecf3-49b7-a5b2-7cd128fc6135
            # sudo apt-get update
            az account set --subscription 1ce8bf33-286c-42dd-b193-10c310dd14b7
            az aks get-credentials --resource-group speakeasy --name speakeasy
            kubectl apply -f deployment.yml
            kubectl set image deployment/nodejs nodejs-aks-app=abhishek00007/newnode:$CIRCLE_BUILD_NUM


workflows:
  testing:
    jobs:
      - buildAndPush
      - deployment
          # requires:
          #   - buildAndPush

