version: 2.1

jobs:
  buildAndPush:
    docker:
      - image: cimg/base:2021.04
    steps:   
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building docker image
          command: |
            echo $docker_password | docker login -u $DOCKERHUB_USERNAME --password-stdin
            GIT_COMMIT=$(git rev-parse --short HEAD)
            docker build -t abhishek00007/newnode:$GIT_COMMIT .
            docker push abhishek00007/newnode:$GIT_COMMIT
  deployment:
    docker:
      - image: abhishek00007/runner1
    steps:
      - checkout
      - run:
          name: deploy-to-AKS
          command: |   
            GIT_COMMIT=$(git rev-parse --short HEAD)
            az login --service-principal -u $client_id -p $client_secret --tenant $tenant_id
            az account set --subscription $subscription
            az aks get-credentials --resource-group speakeasy --name demo-aks
            kubectl apply -f deployment.yml
            kubectl apply -f service.yml
            kubectl set image deployment/nodejs nodejs-aks-app=abhishek00007/newnode:$GIT_COMMIT


workflows:
  testing:
    jobs:
      - buildAndPush
      - deployment:
          requires:
            - buildAndPush

