version: '2.1'
orbs:
  docker: circleci/docker@2.4.0

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/login:
          username: abhishek00007
          password: abhishek@123
      - docker/publish:
          dockerfile: Dockerfile
          image: abhishek00007/org-node:latest
          path: .
          registry: https://hub.docker.com/
