version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
      - run: docker login -u abhishek00007 -p abhishek@123
      - run: docker build -t abhishek00007/newnode .
      - run: docker push abhishek00007/newnode
