version: 2.1

jobs:
  runner-test:
    docker:
      - image: circleci/node:12
    steps:
     - add_ssh_keys:
         fingerprints:
           - "2f:72:fa:ca:c5:7e:3d:26:f3:95:f1:0a:bb:1e:6b:1f"
     - run:
          name: Start SSH
          command: echo 'Starting SSH...'
          background: true    
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Building docker image
          command: |
            echo $docker_password | docker login -u abhishek00007 --password-stdin
            docker build -t abhishek00007/newnode .
            docker push abhishek00007/newnode
            
workflows:
  testing:
    jobs:
      - runner-test
            
            
            
